pkg/github/client/credentials.go
Removing the redundant check for the git token that breaks in open-source repos where there is no need for a token
**TODOs**:
=> :bug: Remove redundant check for git token

pkg/github/client/github_client.go
Two bugs happen with public repos and no git token set:
- isPrivateRepo does not work as an error is returned if the git client was not successfully built. This commit replaces the utility function.
- there was no handling of redirects that Github API gives us for downloading release assets in the case of public repos. This commit adds it.
**TODOs**:
=> :bug: Fix Git client for public repos

README.md
Adding readme that explains the basic components and functionality of the operator and gives references to related projects
**TODOs**:
=> :book: Add basic readme

Makefile, internal/test/integration/github/integration_suite_test.go, internal/test/integration/github/integration_test.go, pkg/test/utils/conditions.go
This PR adds integration tests to test the release asset download flow from github
Fixes #
**TODOs**:
=> 🌱 Add github integration tests

cmd/main.go, config/rbac/role.yaml, internal/controller/clusteraddoncreate_controller.go, internal/controller/clusteraddoncreate_controller_test.go, internal/controller/controller_suite_test.go
Adding the controller that is responsible for creating clusterAddon objects for each cluster object in the management cluster.
Fixes #25 
**TODOs**:
=> :sparkles: Add clusteraddoncreate controller

README.md, cmd/main.go, config/crd/kustomization.yaml, config/cso/cluster.yaml, config/rbac/role.yaml, go.mod, hack/kind-dev.sh, internal/controller/clusteraddon_controller.go, internal/controller/clusterstackrelease_controller.go, pkg/release/release.go, pkg/workloadcluster/restconfig.go
Add clusteraddon controller which is responsible for reconciling ClusterAddons. It templates the ClusterAddon Helm Chart from the cluster stack assets and applies its objects. It also updates the objects if the Helm Chart has been updated and only then - not necessarily on each update of a ClusterStack version.
Fixes #15
**TODOs**:
=> :sparkles: Add clusteraddon controller

internal/controller/clusteraddon_controller.go, pkg/kube/helpers.go, pkg/kube/kube.go, pkg/kube/mocks/Client.go
There are two problems with deleting resources from Helm charts right now: The first one is that the objects stay in the status.resources list, even after they are deleted. The second is that instead of returning an error when a deletion failed, we returned an error on success.
Instead, as we base deletion of objects based on the status.resources list (this can be changed in the future), we keep resources that are supposed to be deleted but failed to in the status as not-synced. Additionally, we requeue and try the deletion another time, just as we do with applying currently.
As the current Update method is unused since we changed from create to apply, it is deleted. Mocks are generated freshly as well.
**TODOs**:
=> :bug: Fix deleting resources from Helm charts

.github/workflows/test.yml, Makefile, internal/test/integration/workloadcluster/cluster_addon_test.go, internal/test/integration/workloadcluster/controller_suite_test.go
Adding integration tests for clusteraddon controller that use the separate kind cluster.
Fixes #46
**TODOs**:
=> :sparkles: Add clusteraddon integration tests

api/v1alpha1/clusterstack_types.go, config/crd/bases/clusterstack.x-k8s.io_clusterstacks.yaml, go.mod, hack/kind-dev.sh, internal/clusterstackrelease/util.go, internal/controller/clusteraddon_controller.go, internal/controller/clusterstack_controller.go, internal/controller/clusterstack_controller_test.go, pkg/clusterstack/clusterstack.go, pkg/release/release.go, pkg/version/channel.go, pkg/version/version.go
=> ✨ Add hash mode compatibility

config/cso/cluster.yaml, config/cso/clusterstack.yaml, docs/develop/develop.md, hack/kind-dev.sh
This PR changes the kind cluster, so that the docker socket of the host is available in the mgt-cluster.
Otherwise, you get:
> Reconciler error" err="failed to create helper for managing the
> externalLoadBalancer: failed to list containers: failed to list containers:
> failed to list containers: Cannot connect to the Docker daemon
>  at unix:///var/run/docker.sock. Is the docker daemon running?
=> :seedling: use v2 for `make tilt-up` and provide Docker socket

internal/controller/clusterstack_controller.go, internal/controller/clusterstackrelease_controller.go
create github client only when required. 
Fixes #58 
**TODOs**:
=> 🌱 create github client only if required

internal/controller/clusterstackrelease_controller.go
defer works even when there's a panic so we are
always unlocking the mutex.
Fixes https://github.com/SovereignCloudStack/cluster-stack-operator/issues/69
**TODOs**:
=> 🐛 defer unlocking of mutex

extension/config/default/sa-roles.yaml, extension/go.mod, extension/go.sum, extension/handlers/hooks.go, extension/main.go, extension/vendor/github.com/SovereignCloudStack/cluster-stack-operator/api/v1alpha1/clusterstack_types.go, extension/vendor/github.com/SovereignCloudStack/cluster-stack-operator/pkg/version/channel.go, extension/vendor/github.com/SovereignCloudStack/cluster-stack-operator/pkg/version/version.go, extension/vendor/modules.txt
=> 🐛 Fix hook server service account and scheme

hack/upgrade-builder-image.sh
when I initially worked on this, this was hardcoded and we were using grep + sed combination to get
version. Later we switched to track version by
using a file at the root of the repo.
The file was .builder-image-version.txt, this was
a bug where we were still reading from Makefile
hardcoded version.
This commit fixes the same and switches to new
method where we read from .builder-image-version.txt
=> 🐛 fix upgrade builder image script

.github/workflows/release.yml
Fixes #99
- **use cosign attest and upgrade bom**
this commit does two things:
1. upgrades kubernetes-sigs/bom to the latest version.
2. It uses cosign attest as replacement to deprecated cosign attach
command.
Signed-off-by: kranurag7 <anurag.kumar@syself.com>
=> :seedling: use cosign attest and upgrade bom

.github/workflows/schedule-update-bot.yaml, hack/upgrade-builder-image.sh
- **allow renovate to propagate builder image version**
As of now, renovate only populates the updated
version in github workflows but don't write
to .builder-image-version.txt which is the main
part.
This commit fixes the same.
Signed-off-by: kranurag7 <anurag.kumar@syself.com>
=> :seedling: allow renovate to propagate builder image version

docs/architecture/user-flow.md
Currently the link to the quickstart guide
from the 'Deep dive: User flow' document is
broken.
This commit fixes the link.
=> :book: fix link to quickstart documentation

Makefile, Tiltfile, capd.yaml
users on fedora using btrfs filesystem were having issues with capd and that was fixed on main and it requires building your own image and using the same here for now.
I tested it by building the image locally and now I don't see any error. This will be fixed when we upgrade to 1.6.3 or later version. As of now, we will rely on image built from CAPI main branch and pushed to ghcr.io/sovereigncloudstack/capd with 1.0.5 tag.
=> 🌱 use scs capd image while using docker provider

.yamllint.yaml, internal/controller/clusteraddon_controller.go
=> 🌱 Remove helmchartstatus after hook is finished

internal/controller/clusteraddon_controller.go, pkg/kube/kube.go
Add debug log information in the addon controller
Fixes #140 
**TODOs**:
=> 🌱 Add debug logs for the multi stage addon

internal/controller/clusteraddon_controller.go, pkg/kube/fake/kube.go, pkg/kube/kube.go, pkg/kube/mocks/Client.go
Adding status.resources to show better potential problems when objects are applied.
Fixes #142
**TODOs**:
=> :sparkles: Add status resources for the helm charts

api/v1alpha1/clusteraddon_types.go, config/crd/bases/clusterstack.x-k8s.io_clusteraddons.yaml, internal/controller/clusteraddon_controller.go
use old release kubernetes version from the metadata.yaml
Fixes #146
**TODOs**:
=> :seedling: Remove kubernetes version from cluster addon api

api/v1alpha1/clusteraddon_types.go, config/crd/bases/clusterstack.x-k8s.io_clusteraddons.yaml, internal/controller/clusteraddon_controller.go, internal/test/integration/workloadcluster/cluster_addon_test.go
Remove status.currentHook from the cluster addon
Fixes #150
**TODOs**:
=> :seedling: Remove status.currentHook from the cluster addon

docs/develop/releasing.md
Fixes https://github.com/SovereignCloudStack/cluster-stack-operator/issues/62
**TODOs**:
=> 📖 add docs for releasing cluster-stack-operator

internal/controller/clusteraddon_controller.go
In the previous PR we introduced a bug that resets the status in every reconcile loop as long as a hook is specified.
However, we only want to reset it once when the hook is new. 
Fixes #154
**TODOs**:
=> :bug: Fix reset of HelmChartStatus of ClusterAddon

internal/controller/clusterstackrelease_controller.go
Fix delete of ClusterStackRelease object in case there is a problem with the release assets.
Currently, the reconcileDelete function requires assets to be downloaded properly. If this is not the case, then the object does not get deleted and is stuck forever.
This happens for example when a user specifies a version of a clusterstack that does not exist. Then a ClusterStackRelease object is created, but will never get deleted again, because the downloading of the release assets fails, as the release does not exist.
Now we have an additional check to remove the finalizer without any further logic in case there is an issue with the release assets.
Fixes #72
**TODOs**:
=> :bug: Fix delete of csr if assets cannot be downloaded

api/v1alpha1/clusteraddon_types.go, internal/controller/clusteraddon_controller.go, pkg/kube/helpers.go, pkg/kube/kube.go, pkg/release/release.go, test/cluster-stacks/2/docker/ferrol/1-27/clusteraddon.yaml, test/cluster-stacks/2/docker/ferrol/1-27/csmctl.yaml
=> :sparkles: Remove unwanted objects during upgrade with hook server

.github/renovate/golang.json5
this should only be updated with CAPI bump PRs. 
fixes these types of PRs https://github.com/SovereignCloudStack/cluster-stack-operator/pull/116
Fixes #
**TODOs**:
=> 🌱 disable core k8s deps bumps via renovate

internal/controller/clusteraddon_controller.go
Currently, we set the clusterAddon on ready always. we want to do that only at the end of a flow.
**TODOs**:
=> :seedling: Set clusterAddon on ready only if required

api/v1alpha1/conditions_const.go, internal/controller/clusteraddon_controller.go
Adding a condition that indicates that we wait for the hook server or that the hook server is responsive.
Fixes #193
**TODOs**:
=> :seedling: Add condition if waiting for hook server

internal/controller/clusterstack_controller.go, pkg/clusterstack/clusterstack.go
- clusterstack.status.latestRelease & clusterstack.status.usableVersion use semver ("." notation)
Fixes #221 
**TODOs**:
=> 🌱 Use semver version in cluster stack status

Makefile, Tiltfile, api/v1alpha1/cluster_webhook.go, api/v1alpha1/clusteraddon_webhook.go, api/v1alpha1/clusterstack_webhook.go, api/v1alpha1/clusterstackrelease_webhook.go, api/v1alpha1/webhook.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/main.go, config/default/kustomization.yaml, config/localmode/kustomization.yaml, config/webhook/manifests.yaml, go.mod, internal/controller/clusteraddon_controller_test.go, internal/controller/clusteraddoncreate_controller_test.go, internal/controller/clusterstack_controller_test.go, internal/controller/clusterstackrelease_controller_test.go, internal/controller/controller_suite_test.go, internal/test/helpers/envtest.go, internal/test/helpers/webhook.go, pkg/kube/mocks/KFactory.go, pkg/workloadcluster/fake/restconfig.go, vendor/github.com/MakeNowJust/heredoc/LICENSE, vendor/github.com/MakeNowJust/heredoc/README.md, vendor/github.com/MakeNowJust/heredoc/heredoc.go, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api/util/yaml/yaml.go
- this PR adds webhooks for resources 
Fixes https://github.com/SovereignCloudStack/cluster-stack-operator/issues/13
**TODOs**:
=> ✨ add webhooks for resources 

internal/controller/clusteraddon_controller.go, internal/controller/clusteraddon_controller_test.go, internal/controller/clusteraddoncreate_controller_test.go, internal/controller/clusterstackrelease_controller.go, internal/controller/clusterstackrelease_controller_test.go, pkg/kube/fake/kube.go, pkg/kube/kube.go, pkg/kube/mocks/Client.go
=> 🌱 Removing the temporary shouldDelete option to kubeClient.Apply that was not used anyway and always set on true

internal/controller/clusteraddon_controller.go
Helm charts can use `Capabilities.KubeVersion`.
Fixes SovereignCloudStack/cluster-stacks#143
**TODOs**:
=> :sparkles: Include Kubernetes version in helm template

internal/controller/clusterstack_controller.go
If a release in the Github repo is not following the correct naming pattern of cluster stack releases, then up to now the the process failed.
This PR creates a Kuberentes Event, and then continues with the next release of the list.
Fixes #231 
**TODOs**:
=> :bug: Fix issue 231: Continue if cluster stack string is invalid

api/v1alpha1/conditions_const.go, internal/controller/clusteraddon_controller.go
Add a condition to mark an invalid clusteraddon.yaml. Also add an event.
Fixes #208
**TODOs**:
=> :seedling: Use condition to mark false clusteraddon.yaml

internal/controller/clusterstackrelease_controller.go, pkg/release/release.go
Currently the return of helmChartNamePath is not checked on errors. This means that the CSO tries to helm template the container which leads to cryptic error messages from helm.
This commit adds a check on errors on the call to helmChartNamePath and results in more helpful error messages by helm.
Fixes #288 
The log message after the patch is more helpful:
```
{"level":"ERROR","time":"2025-04-14T15:28:57.491Z","file":"controller/controller.go:324","message": …
```
=> :bug: Fix: Handle empty chart directory correctly
